-- EIA Weekly Petroleum Status Report (WPSR) warehouse
--
-- Two fact stores, both fed by ingest/eia_ingest.py:
--
--   series + observation  full history (1982 -> present) parsed from the WPSR
--                         .xls workbooks, keyed by EIA's canonical sourcekey.
--   csv_snapshot          the current week's published table cells parsed from
--                         the WPSR .csv files, including EIA's own week-over-week
--                         and year-over-year deltas exactly as printed.

CREATE TABLE IF NOT EXISTS series (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sourcekey    text NOT NULL,             -- EIA series id, e.g. WCRFPUS2, RWTC
    name         text NOT NULL,             -- full descriptive name from the workbook
    short_name   text NOT NULL DEFAULT '',  -- name with unit/frequency noise stripped
    unit         text NOT NULL DEFAULT '',  -- e.g. Thousand Barrels per Day
    frequency    text NOT NULL DEFAULT '',  -- daily | weekly | 4-week average
    table_id     text NOT NULL,             -- WPSR table number: 1,2,...,9,11,12,14
    table_title  text NOT NULL DEFAULT '',
    sheet        text NOT NULL DEFAULT '',  -- workbook sheet, e.g. "Data 3"
    sheet_title  text NOT NULL DEFAULT '',
    category     text NOT NULL DEFAULT 'other',  -- production|stocks|imports|...
    area         text NOT NULL DEFAULT '',       -- U.S. | PADD 1 | Cushing | ...
    product      text NOT NULL DEFAULT '',       -- Crude Oil | Motor Gasoline | ...
    first_period date,
    last_period  date,
    obs_count    integer NOT NULL DEFAULT 0,
    UNIQUE (sourcekey, name)
);

-- A series is stored once, but EIA publishes many of them in several tables
-- (table 9 restates most of tables 1-7). This records every place a series
-- appears, so each source sheet can be reproduced in full without duplicating
-- 670k observations. series.table_id/sheet hold the canonical (lowest-numbered)
-- source for display.
CREATE TABLE IF NOT EXISTS series_source (
    series_id   integer NOT NULL REFERENCES series (id) ON DELETE CASCADE,
    table_id    text NOT NULL,
    table_title text NOT NULL DEFAULT '',
    sheet       text NOT NULL,
    sheet_title text NOT NULL DEFAULT '',
    col_idx     smallint NOT NULL DEFAULT 0,
    PRIMARY KEY (series_id, table_id, sheet)
);

CREATE INDEX IF NOT EXISTS series_source_sheet_idx ON series_source (table_id, sheet);

CREATE INDEX IF NOT EXISTS series_category_idx ON series (category);
CREATE INDEX IF NOT EXISTS series_table_idx    ON series (table_id);
CREATE INDEX IF NOT EXISTS series_freq_idx     ON series (frequency);
CREATE INDEX IF NOT EXISTS series_sourcekey_idx ON series (sourcekey);

CREATE TABLE IF NOT EXISTS observation (
    series_id integer NOT NULL REFERENCES series (id) ON DELETE CASCADE,
    period    date NOT NULL,
    value     double precision NOT NULL,
    PRIMARY KEY (series_id, period)
);

CREATE INDEX IF NOT EXISTS observation_period_idx ON observation (period);

-- Current-week snapshot straight from the WPSR CSVs.
-- column_kind separates real observations from EIA's derived comparison columns.
CREATE TABLE IF NOT EXISTS csv_snapshot (
    report_date  date NOT NULL,      -- week ending covered by the report
    table_id     text NOT NULL,
    section      smallint NOT NULL,  -- CSVs contain multiple stacked tables
    row_idx      smallint NOT NULL,
    col_idx      smallint NOT NULL,
    row_path     text NOT NULL,      -- 'Refiner Inputs > Percent Utilization > PADD 1'
    row_label    text NOT NULL,      -- leaf only
    column_label text NOT NULL,      -- as printed: '7/31/26', 'Difference', ...
    column_kind  text NOT NULL,      -- observation|difference|percent_change|share
    period       date,               -- set when column_kind = 'observation'
    value        double precision,
    PRIMARY KEY (report_date, table_id, section, row_idx, col_idx)
);

CREATE INDEX IF NOT EXISTS csv_snapshot_table_idx ON csv_snapshot (table_id, section);

CREATE TABLE IF NOT EXISTS ingest_run (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at   timestamptz NOT NULL DEFAULT now(),
    finished_at  timestamptz,
    mode         text NOT NULL,          -- xls | csv | all
    status       text NOT NULL DEFAULT 'running',
    series_seen  integer NOT NULL DEFAULT 0,
    rows_written integer NOT NULL DEFAULT 0,
    report_date  date,
    message      text
);

-- Latest / prior / year-ago per series, for the dashboard's stat tiles.
-- Refreshed at the end of every ingest run.
CREATE MATERIALIZED VIEW IF NOT EXISTS series_latest AS
WITH ranked AS (
    SELECT o.series_id,
           o.period,
           o.value,
           row_number() OVER (PARTITION BY o.series_id ORDER BY o.period DESC) AS rn
    FROM observation o
),
latest AS (
    SELECT series_id, period, value FROM ranked WHERE rn = 1
),
prior AS (
    SELECT series_id, period, value FROM ranked WHERE rn = 2
)
SELECT s.id AS series_id,
       l.period                AS latest_period,
       l.value                 AS latest_value,
       p.period                AS prior_period,
       p.value                 AS prior_value,
       ya.period               AS year_ago_period,
       ya.value                AS year_ago_value
FROM series s
JOIN latest l ON l.series_id = s.id
LEFT JOIN prior p ON p.series_id = s.id
LEFT JOIN LATERAL (
    SELECT o.period, o.value
    FROM observation o
    WHERE o.series_id = s.id
      AND o.period <= l.period - INTERVAL '1 year'
    ORDER BY o.period DESC
    LIMIT 1
) ya ON true;

CREATE UNIQUE INDEX IF NOT EXISTS series_latest_pk ON series_latest (series_id);

-- Denormalised convenience view for ad-hoc SQL: every observation with the
-- metadata you would otherwise join for. Filter it by table_id/category/area
-- to get "just one source" without storing the data that way.
CREATE OR REPLACE VIEW v_observation AS
SELECT s.table_id,
       s.table_title,
       s.sheet,
       s.sheet_title,
       s.sourcekey,
       s.short_name,
       s.name,
       s.unit,
       s.frequency,
       s.category,
       s.area,
       s.product,
       o.period,
       o.value
FROM observation o
JOIN series s ON s.id = o.series_id;

-- In addition, ingest/eia_ingest.py generates one wide view per source sheet
-- (wpsr_t9_data3, wpsr_t11_data1, ...) with a column per EIA sourcekey, so the
-- familiar spreadsheet shape is queryable without storing 38% NULL padding.
--   SELECT period, "RWTC", "RBRTE" FROM wpsr_t11_data1 ORDER BY period DESC;
